### ISSUE TITLE
tkey and tsecret

### ISSUE THREAD

**Issue by misterrichie** [rmgirardin/mouse-bot#1]
I am not sure where to find this info.

**Comment by rmgirardin** [comment]
I've removed the twitter function, forgot to update the config file. I'm considering bringing it back. If I do, I'll probably supply the key and secret for a generic twitter bot.

**Comment by misterrichie** [comment]
Im having problems still getting it to install on terminal. I get syntax
errors. Something not catching.

**Comment by rmgirardin** [comment]
Hmmm, not sure why. If you want to add me on Discord I can try to help you out. Necavit#0540
