### ISSUE TITLE
app.js in instructions

### ISSUE THREAD

**Issue by LambKyle** [rmgirardin/mouse-bot#2]
Instructions say "Now you can use node app.js in the terminal in your mouse-bot directory folder. Alternatively you can use node and drag the folder path into the terminal."

But the file isn't called app.js, it's called index.js

Unless I'm being stupid and don't understand. When I try typing 'node app.js' in the node.js command prompt it says "Error: Cannot find module"

**Comment by rmgirardin** [comment]
You're correct! You need to run `node index.js` for it to run. I'll be uploading v2.0 next week and that will be corrected. Thank you!
