### ISSUE TITLE
SWGoH.gg Usernames w/Special Character(s)

### ISSUE THREAD

**Issue by dajhmaster** [rmgirardin/mouse-bot#3]
SWGoH.gg usernames with special character(s) throw an error when using for the 'profile' command.

**Comment by dajhmaster** [comment]
The %20 gets converted to a space, so that returns an error when building the Discord embed (authorURL). A simple fix for me was to pull in ${id} instead of ${profile.username.toLowerCase()}.

**Comment by rmgirardin** [comment]
This is with the .setURL of the embed? The URLs on the site convert spaces. Is the link not working or can you not lookup the profile?

**Comment by dajhmaster** [comment]
The profile returns fine, but throws an error when setting the authorURL for the embed. This is because the URL has spaces when pulled from ${profile.username.toLowerCase()}.

**Comment by backjoe** [comment]
I can resolv this. 
const collection = await swgoh.collection(encodeURI(id));
Thanks.

**Comment by rmgirardin** [comment]
Fix has been pushed. Should also work with Japanese characters now, too. Thank you!
